name: Build, Test, and Deploy

on:
  push:
    branches: "Prod"
  pull_request:
    branches: "Prod"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Construir con Maven
        run: mvn clean install

      - name: Ejecutar pruebas
        run: mvn test

      - name: Crear jar y ejecutar app
        run: mvn verify

