name: CI

on:
  push:
    branches: [ "Prod" ]
  pull_request:
    branches: [ "Prod" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: x64

    - name: Compilar y ejecutar tests
      run: mvn clean test

    - name: Realizar build
      run: mvn clean package

    - name: Crear jar y ejecutar app
      run: mvn verify
