name: CI

on:
  push:
    branches:
      - Prod
  pull_request:
    branches:
      - Prod
  workflow_call:
    secrets:
      access-token:
        description: '180401'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Pass the received secret to an action
        uses: ./.github/actions/CI
        with:
          token: ${{ secrets.access-token }}

      - name: Checkout del código fuente
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64

      - name: Compilar y ejecutar tests
        run: mvn clean test

      - name: Realizar build
        run: mvn clean package

      - name: Crear jar y ejecutar app
        run: mvn verify

      - name: Crear solicitud de extracción
        if: success()
        run: |
          # Configurar las variables necesarias
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH="Prod"
          BASE_BRANCH="main"  # Reemplaza 'main' por la rama base que desees
          
          # Crear la solicitud de extracción usando la API de GitHub
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Nicbag/Ing.Software/pulls \
            -d '{
              "title": "Nueva funcionalidad",
              "head": "'${{ BASE_BRANCH }}'",
              "base": "'$TARGET_BRANCH'",
              "body": "Esta es una nueva funcionalidad."
            }'

  # Agregado el siguiente paso para pasar el secreto a otro flujo de trabajo
  pass-secret-to-workflow:
    uses: ./.github/workflows/config
    secrets:
      token: ${{ secrets.access-token }}
