name: CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
  workflow_call:
    secrets:
      access-token:
        description: '180401'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Pass the received secret to an action
        uses: ./.github/actions/CI
        with:
          token: ${{ secrets.access-token }

      - name: Checkout del código fuente
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64

      - name: Compilar y ejecutar tests
        run: mvn clean test

      - name: Realizar build
        run: mvn clean package

      - name: Crear jar y ejecutar app
        run: mvn verify

      - name: Crear solicitud de extracción
        if: success()
        run: |
          # Configurar las variables necesarias
          GITHUB_TOKEN=${{ secrets.CIRO }}
          TARGET_BRANCH="Dev"
          
          # Crear la solicitud de extracción usando la API de GitHub
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Nicbag/Ing.Software/pulls \
            -d '{
              "title": "Nueva funcionalidad",
              "head": "'$GITHUB_REF'",
              "base": "'$TARGET_BRANCH'",
              "body": "Esta es una nueva funcionalidad."
            }'

pass-secret-to-workflow:
  uses: ./.github/workflows/config
  secrets:
    token: ${{ secrets.access-token }}






